config/routes.rb
Rails.application.routes.draw do
  
  resources :dandelions do
    get :openValve, on: :collection
    get :closeValve, on: :collection
  end

  get 'sunflowers/show' => 'sunflowers#show'
  get 'sunflowers/' => 'sunflowers#index'
  get 'sunflowers/index' => 'sunflowers#index'
  get 'sunflowers/irrigation' => 'sunflowers#irrigation'

  get 'dandelions/:id' => 'dandelions#show'
  get 'dandelions/show' => 'dandelions#show'
  get 'dandelions/' => 'dandelions#index'
  get 'dandelions/index' => 'dandelions#index'

end

app/models/dandelion.rb
class Dandelion < ActiveRecord::Base
has_many :reports
end

app/models/dandelion_statuses.rb
class DandelionStatuses < ActiveRecord::Base
end

app/models/peeper.rb
class Peeper < ActiveRecord::Base
end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :dandelion
end

app/models/sunflower.rb
class Sunflower < ActiveRecord::Base
  has_many :valves
  has_many :dandelions
  #has_many :reports through :dandelions
  #has_many :valve_reports through :valves
end

app/models/valve_reports.rb
class ValveReports < ActiveRecord::Base
  belongs_to :valve
end

app/models/valve_statuses.rb
class ValveStatuses < ActiveRecord::Base
end

app/models/valves.rb
class Valves < ActiveRecord::Base
  belongs_to :sunflower
  has_many :valve_reports
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dandelionreports_controller.rb
class DandelionreportsController < ApplicationController
# access at /dandelionreports
  # the data should be sent as part of the request body.
  def create
    @dandelionreports = DandelionReport.new(params[:dandelionreport])
    reportData = @dandelionreports.split('\n') 
    reportData.each do |d|
      ent = d.split(',')
	    r = Report.create({ :moisture1 => ent[0], :moisture1 => ent[1],  })
      r.moisture1 = ent[0]
      r.moisture2 = ent[1]
      r.moisture3 = ent[2]
      r.humidity = ent[3]
      r.temperature = ent[4]
	    r.batterylevel = ent[5]
      r.reporttime = ent[6]
	    r.dandelionid = ent[7]
	    r.stateid = ent[8]
    end
    # issue a standard HTTP Status Code 202 (accepted) reponse to the request
    render :accepted
  end
end

app/controllers/dandelions_controller.rb
class DandelionsController < ApplicationController
  layout "application"
#list all dandelion data
  def index
    @dandelions = Dandelion.all
    @reports = Array.new(@dandelions.length)
    $i = 0

    while $i < @dandelions.length do
     @reports[$i] = Report.where(dandelionid: @dandelions[$i].id).last
       @reports[$i].moisture1 = '%.2f' % @reports[$i].moisture1
       @reports[$i].moisture2 = '%.2f' % @reports[$i].moisture2
       @reports[$i].moisture3 = '%.2f' % @reports[$i].moisture3
       @reports[$i].humidity  = '%.3f' % @reports[$i].humidity
       $i +=1
    end

    respond_to do |format|
      format.html 
      format.json { render json: @dandelions }
    end
  end

#show individual dandelion data 
  def show
    @dandelions = Dandelion.all
    @allReports = Array.new(@dandelions.length)
    @moistureStatus = Array.new(@dandelions.length)
    @humidityStatus = Array.new(@dandelions.length)
    @irrigationStatus = Array.new(@dandelions.length)
    @secondReport = Array.new(@dandelions.length)
    @wateringTime = Array.new(@dandelions.length)
    @m0 = Array.new(@dandelions.length)
    @m1 = Array.new(@dandelions.length)
    @mt = Array.new(@dandelions.length)

    $j = 0
    while $j < @dandelions.length do
      @allReports[$j] = Report.where(dandelionid: @dandelions[$j].id).last
      @lastReport = Report.where(dandelionid: @dandelions[$j].id).last(2)
      @secondReport[$j] = @lastReport[0]
      @allReports[$j].moisture1 = '%.2f' % @allReports[$j].moisture1
      #moisture
      @moistureDifference = (@allReports[$j].moisture1 + @allReports[$j].moisture2 + @allReports[$j].moisture3)/3 - @dandelions[$j].moistureLimit
      if @moistureDifference > 0.2
        @moistureStatus[$j] = 'well above the threshold'
        @irrigationStatus[$j] = 'No action needed'
      elsif @moistureDifference <= 0.2 and @moistureDifference > 0
        @moistureStatus[$j] = 'close to limit'
        @irrigationStatus[$j] = 'Irrigation soon'
      elsif @moistureDifference <= 0 and 
        @moistureStatus[$j] = 'below limit'
        @irrigationStatus[$j] = 'Irrigate needed'
      end

      #humidity
      if @allReports[$j].humidity > 0.75
        @humidityStatus[$j] = 'very high.'
      elsif @allReports[$j].humidity <= 0.75  and @allReports[$j].humidity > 0.5
        @humidityStatus[$j] = 'high.'
      elsif @allReports[$j].humidity <= 0.5  and @allReports[$j].humidity > 0.25
        @humidityStatus[$j] = 'moderate.'
      elsif @allReports[$j].humidity <= 0.25
        @humidityStatus[$j] = 'low.'
      end

      #wateringSchedule
      @mt[$j] = @dandelions[$j].moistureLimit
      @m0[$j] = (@allReports[$j].moisture1 + @allReports[$j].moisture2 + @allReports[$j].moisture3)/3
      @m1[$j] = (@secondReport[$j].moisture1 + @secondReport[$j].moisture1 + @secondReport[$j].moisture1)/3
      @deltaT = 10;
      @wateringTime[$j] = ((@m0[$j]-@mt[$j])*(@deltaT))/(@m1[$j]-@m0[$j])
      if @wateringTime[$j] < 0 and @moistureDifference < 0
        @wateringTime[$j] = "is required immediately."
      elsif @wateringTime[$j] < 0 and @moistureDifference >=0
        @wateringTime[$j] = "occurred recently, new schedule is being calculated."
      else
        @temp =  '%.0f' % @wateringTime[$j]
        @wateringTime[$j] = 'should occur in approximately ' + @temp + ' minutes.'
      end
      $j +=1
    end

    if params[:id] == 'irrigation'
       render :action =>'irrigation'

    else
      @dandelion = Dandelion.find(params[:id])
      @reports = Report.where(dandelionid: params[:id]).last(72)
      @lastReport = Report.where(dandelionid: params[:id]).last

      respond_to do |format|
        format.html { render layout: "individual" }
        format.json { render json: @reports }
      end
    end
  end

  def irrigation
  end
  
  def openValve
    @id = params[:valveID]
    @result = system("python sunflower-interface.py --open " + @id)
    render :text => "success"
  end

  def closeValve
    @id = params[:valveID]
    @result = system("python sunflower-interface.py --close "+ @id)

    render :text => "success"
    puts "success"+@id
  end
  
  private
  def dandelion_params
    ##params.require(:article).permit(:name, :uuid, etc)
  end
end

app/controllers/sunflowers_controller.rb
class SunflowersController < ApplicationController
  def index
  	@sunflowers = Sunflower.all
    @result = system("python sunflower-interface.py --open 0")

  end

  def show
  @sunflower = Sunflower.find('24f7b3b3-4782-4f40-b849-2262fc56608d')
	@dandelions = Dandelion.where(sunflowerID: '24f7b3b3-4782-4f40-b849-2262fc56608d')
	$i = 0
	@reports = Array.new(@dandelions.length)
    while $i < @dandelions.length  do
       @reports[$i] = Report.where(dandelionid: @dandelions[$i].id).last
       $i +=1
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dandelion_reports_helper.rb
module DandelionReportsHelper
end

app/helpers/dandelionreports_helper.rb
module DandelionreportsHelper
end

app/helpers/dandelions_helper.rb
module DandelionsHelper
end

app/helpers/sunflowers_helper.rb
module SunflowersHelper
end

app/views/dandelions/index.html.erb
<section class="data-wrapper right"> 		
	<div class="data-content content-wrapper">
		<!-- header -->
		<div class="data-content-header" id="all-sensor">
			<h2>Sensor Data Sheet</h2>
			<div class="content-divider"></div>
			<ul class="data-toggle">
				<li id="toggle-list" class="opacityUp"><img src="/assets/list.svg"></li>
				<li id="toggle-grid"><img src="/assets/grid.svg"></li>
			</ul>
		</div>
		<div class="dandelion-data list-view" id="dandelion-view">
			<!-- titles -->
			<ul class="list-view-header">
				<li class="header-sensor">Sensor</li>
				<li class="header-air-temp">Air Temp</li>
				<li class="header-soil-temp">Soil Temp<br>
					<span>Level 1</span>
					<span>Level 2</span>
					<span>Level 3</span>
				</li>
				<li class="header-humidity">Humidity</li>
				<li class="header-moisture">Moisture<br>
					<span>Level 1</span>
					<span>Level 2</span>
					<span>Level 3</span>
				</li>
			</ul>
			<!-- content -->
			<ul class="dandelion-listing">
				<% i = 1 %>
					<% @reports.each do |report| %>
					<%= link_to dandelion_path(@dandelions[i-1]) do %>
						<li class="dandelion-listing-item">		
							<ul>
								<h3 class="sensor">Dandelion<span>#<%= i %></span></h3>
								<li class="air-temp">
									<p>21<span>&nbsp;</span></p>
									<h4>Humidity</h4>
								</li>
								<li class="soil-temp multiple-list">
									<p><%= report.temperature1 %><span>Level 1</span></p>
									<p><%= report.temperature2 %><span>Level 2</span></p>
									<p><%= report.temperature3 %><span>Level 3</span></p>
									
									<h4>Soil Temp</h4>
								</li>
								<li class="humidity">
									<p><%= report.humidity %> <span>&nbsp;</span></p>
									<h4>Humidity</h4>
								</li>
								<li class="moisture multiple-list">
									<p><%= report.moisture1 %> <span>Level 1</span></p>
									<p><%= report.moisture2 %> <span>Level 2</span></p>
									<p><%= report.moisture3 %> <span>Level 3</span></p>
									
									<h4>Moisture</h4>
								</li>
							</ul>
						</li>
						<% i += 1 %>
					<% end %>	
				<% end %>
			</ul>

		</div>
	</div>
</section>

app/views/dandelions/irrigation.html.erb
<section class="data-wrapper right"> 		
<div class="data-content">
<div class="content-wrapper">
	<!-- indiv header -->
	<div class="data-content-header" >
		<h2>Irrigation Information</h2>
		<div class="content-divider"></div>

	</div>

	<div class="dandelion-data list-view" id="dandelion-view">

		<!-- titles -->
		<ul class="list-view-header">
			<li class="header-sensor">Sensor</li>

			<li class="header-moisture-level">Moisture Level</li>
			<li class="header-air-temp">Moisture Limit</li>
			<li class="header-action">Action</li>
			<li class="header-air-temp">Control</li>
		</ul>

		<!-- content -->
		<ul class="dandelion-listing">
			<% i = 1 %>
			<% @allReports.each do |report| %>
				<li class="dandelion-listing-item" id="irrigation-listing">		
					<ul>
						<h3 class="sensor">Dandelion<span>#<%= i %></span></h3>
						<li class="moisture" id="irrigation-moisture">
							<p><%= report.moisture1 %></p>
							<h4>Moisture</h4>
						</li>
						<li class="humidity">
							<p> <%= @dandelions[i-1].moistureLimit %></p>
							<h4>Moisture Limit</h4>
						</li>
						<li class="irrigation-action"><%= @irrigationStatus[i-1] %></li>
						<li class="irrigation-button"><button class="aButton">Irrigate</button></li>
						<li class="irrigation-expand"><img src="/assets/chevron-down.svg"></li>
					</ul>

					<ul class="irrigation-details" style="display: none">
					<h2>Details</h2>
					<li>Soil temperate is <span><%= report.temperature1 %> degrees </span></li>
					<li>Moisture level is  <span><%= @moistureStatus[i-1] %></span></li>
					<li>Humidity is  <span><%= @humidityStatus[i-1] %> </span></li>
					<li>Irrigation <span><%= @wateringTime[i-1] %></span></li>
					</ul>
				</li>
				<% i += 1 %>
			<% end %>
		</ul>
	</div>	

</div>
</div>
</section>

app/views/dandelions/show.html.erb
<section class="data-wrapper right"> 		
	<div class="data-content">
		<div class="content-wrapper">
			<!-- indiv header -->
			<div class="data-content-header" id="indiv-sensor">
				<h2>Sensor: Dandelion <span><% @dandelion.nickname %></span></h2>
				<div class="content-divider"></div>
				<ul class="data-toggle">
  					<li id="toggle-daily" class="active">Daily</li>
  					<li id="toggle-weekly">Weekly</li>
  					<li id="toggle-monthly">Monthly</li>
				</ul>
			</div>
				<!-- <div class="return">Back</div> -->

			<%= link_to image_tag("chevron-left.svg", :border=>0), {:controller => 'dandelions'}, {:class => 'return'} %>

				
			<!-- individual data view -->
			<div class="indiv-sensor-data">
				<ul class="device-metadata">
					<h3 class="sensor">Device Metadata</h3>
					<li class="sensor-img">
						<img src="/assets/sensor-thumb.png">
					</li>
					<li class="battery">
						<p><%= @lastReport.batterylevel %></p>
						<h4>Battery</h4>
					</li>
					<li class="altitude">
						<p><%= @dandelion.alti %>m</p>
						<h4>Altitude</h4>
					</li>
					<li class="firmware-version">
						<p><%= @dandelion.vFirmware %> </p>
						<h4>Firmware Ver.</h4>
					</li>
					<li class="moisture-limit">
						<p><%= @dandelion.moistureLimit %> </p>
						<h4>Mois. Limit</h4>
					</li>
					<li class="longtitude">
						<p><%= @dandelion.longi %></p>
						<h4>Longitude</h4>
					</li>
					<li class="latitude">
						<p><%= @dandelion.lati %> </p>
						<h4>Latitude</h4>
					</li>
				</ul>	
				<div class="moisture-trend">
					<h3 class="sensor">Mositure Level Trend</h3>
					<h4>Measured in % overtime for each level</h4>
					<ul class="legend">
						<li><div class="legend-circle"></div><p>Level 1</p></li>
						<li><div class="legend-circle"></div><p>Level 2</p></li>
						<li><div class="legend-circle"></div><p>Level 3</p></li>
					</ul>

					<div class="moisture-table" id="moisTable">
					</div>			
				</div>
				<div class="humidity-trend">
					<h3 class="sensor">Humidity Trend</h3>
					<h4>Measured in % overtime for each level</h4>
					
					<canvas id="humidity-chart"></canvas>

				</div>
				<div class="soil-temp-trend">
					<h3 class="sensor">Soil Temperature Trend</h3>
					<h4>Measured in % overtime for each level</h4>
					<ul class="legend">
						<li><div class="legend-circle"></div><p>Level 1</p></li>
						<li><div class="legend-circle"></div><p>Level 2</p></li>
						<li><div class="legend-circle"></div><p>Level 3</p></li>
					</ul>
					<canvas id="soil-temp-chart"></canvas>

				</div>
			</div>
			
		</div>
	</div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bouquet</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body  id="page-body">
<%= render "shared/menu" %>
<%= render "shared/map" %>

<%= yield %>

<div class="clearfix"></div>
</body>
<script src="https://maps.googleapis.com/maps/api/js?callback=initMap&key=AIzaSyAGe9B_zL2EM15cQdtdRf1CAWpb8kwPrZw&libraries=visualization"
        async defer></script>

        

</html>
 

app/views/layouts/individual.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bouquet</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body  id="page-body">
<%= render "shared/menu" %>
<%= render "shared/map" %>

<%= yield %>

<div class="clearfix"></div>
</body>
<script src="https://maps.googleapis.com/maps/api/js?callback=initMap"
        async defer></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.min.js"></script>

</html>

app/views/shared/_indivMap.html.erb
<section class="map-wrapper left" id="Map">
  <div id="map-canvas"></div>
</section>

app/views/shared/_map.html.erb
<section class="map-wrapper left" id="map">
	<div id="map-canvas"></div>
</section>

app/views/shared/_menu.html.erb
<ul class="data-nav">
	<li class="data-nav-li menu-sensor active">
		<img src="/assets/nav/sensor.svg">
		<h3>Sensor</h3>
	</li>
	<li class="data-nav-li menu-heatmap">
		<img src="/assets/nav/heatmap.svg">
		<h3>Heatmap</h3>
	</li>
	<li class="data-nav-li menu-irrigation">
		<img src="/assets/nav/irrigation.svg">
		<h3>Irrigation</h3>
	</li>
	<li class="data-nav-li">
		<img src="/assets/nav/settings.svg">
		<h3>Settings</h3>
	</li>
</ul>

app/views/sunflowers/index.html.erb
<h1>Sunflower index view!</h1>

app/views/sunflowers/irrigation.html.erb
<button id="aButton">Press me </button>

app/views/sunflowers/show.html.erb
<h1>Sunflowers#show</h1>
<%= @reports[1].reporttime %>

<p>UUID: <%= @sunflower.id %> <br>
Nickname (label): <%= @sunflower.nickname %> <br>
Firmware Version: <%= @sunflower.vFirmware %> <br>

<h1>Dandelions of this Sunflower</h1>
<table>
	<tr>
	<td>dandelionid</td>
	<td>nickname</td>
	<td>vFirmware</td>
	<td>lati</td>
	<td>longi</td>
	<td>alti</td>
	<td>moistureLimit</td>
	</tr>
<% @dandelions.each do |dandelion| %>
  <tr>  
	<td><%= dandelion.id %></td>
	<td><%= dandelion.nickname %></td>
	<td><%= dandelion.vFirmware %></td>
	<td><%= dandelion.lati %></td>
	<td><%= dandelion.longi %></td>
	<td><%= dandelion.alti %></td>
	<td><%= dandelion.moistureLimit %></td>
  </tr>
  <% end %>
  </table>

<h1>Last Reports</h1>
<table>
	<tr>
	<td>dandelionid</td>
	<td>reporttime</td>
	<td>moisture1</td>
	<td>moisture2</td>
	<td>moisture3</td>
	<td>temperature1</td>
	<td>temperature2</td>
	<td>temperature3</td>
	<td>humidity</td>
	<td>batterylevel</td>
	<td>stateid</td>
	</tr>
<% @reports.each do |report| %>
  <tr>  
	<td><%= report.dandelionid %></td>
	<td><%= report.reporttime %></td>
	<td><%= report.moisture1 %></td>
	<td><%= report.moisture2 %></td>
	<td><%= report.moisture3 %></td>
	<td><%= report.temperature1 %></td>
	<td><%= report.temperature2 %></td>
	<td><%= report.temperature3 %></td>
	<td><%= report.humidity %></td>
	<td><%= report.batterylevel %></td>
	<td><%= report.stateid %></td>
  </tr>
  <% end %>
  </table>
  <br>
  Accessing specific data:<br>
  <%= @reports[0].reporttime %>
</p>